name: Oort (TNO)
favicon: null
layout_spectrum: 0.87137
typography_spectrum: 0.52333
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#5b4c3c'
    - '#dc3a18'
    - '#f2ce2a'
  brandStrength: 1
  lightness: 0.4375
  saturation: 1
  rhythmicContrast: 1
purpose: []
