layout_spectrum: 0.4274873
favicon: null
name: Oort (TNO)
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.8017572299577296
  lightness: 0.2344287901651114
  saturation: 0.2367763556540012
  rhythmicContrast: 0.9477666919119656
  brandColors:
    - '#88030C'
    - '#FFAB54'
    - '#904342'
    - '#BCAC9A'
    - '#FFFDFC'
typography_spectrum: 0.05902192
