layout_spectrum: 0.8920742
favicon: null
name: Oort (TNO)
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
  brandColors:
    - '#4B2720'
    - '#E1B391'
    - '#53789A'
    - '#BDA316'
    - '#FFFFFB'
typography_spectrum: 0.8507589
